[package]
name = "media"
version = "0.1.0"
edition.workspace = true
publish = false
license = "Apache-2.0"
description = "Bindings to macos media handling APIs for Zed"

[lints]
workspace = true

[lib]
path = "src/media.rs"
doctest = false

[[test]]
name = "video_playback"
path = "tests/video_playback.rs"
harness = false

[dependencies]
anyhow.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
block = "0.1"
core-foundation.workspace = true
ctor.workspace = true
foreign-types = "0.5"
metal.workspace = true
core-video.workspace = true
objc.workspace = true
futures.workspace = true
tempfile.workspace = true

[target.'cfg(target_os = "macos")'.dev-dependencies]
smol.workspace = true

[build-dependencies]
bindgen = "0.71"
