#!/usr/bin/env bash

set -euo pipefail

if [[ ! " $* " == *" -p "* && ! " $* " == *" --package "* ]]; then
    set -- "$@" --workspace
fi

case "${FANTA_CLIPPY_DEFAULT_FEATURES-0}" in
    0) set -- "$@" --all-features ;;
    1) ;;
    *)
        printf 'FANTA_CLIPPY_DEFAULT_FEATURES must be 0 or 1.\n' >&2
        exit 2
        ;;
esac

set -x
"${CARGO:-cargo}" clippy "$@" --release --all-targets -- --deny warnings

# If local, run other checks if we have the tools installed.
if [[ -z "${GITHUB_ACTIONS+x}" ]]; then
    which cargo-machete >/dev/null 2>&1 || exit 0
    cargo machete

    which typos >/dev/null 2>&1 || exit 0
    typos --config typos.toml

    which buf >/dev/null 2>&1 || exit 0
    buf lint crates/proto/proto
    buf format --diff --exit-code crates/proto/proto
fi
