name: Check

on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check licenses
        run: ./script/check-licenses

      - name: Check the app builds
        run: cargo check -p zed
